INSERT INTO TBL_STUDENT (NOME, CURSO) VALUES ('Rodrigo Sampaio', 'ADS');
INSERT INTO TBL_STUDENT (NOME, CURSO) VALUES ('Gabriel Barbosa', 'ADS');
INSERT INTO TBL_STUDENT (NOME, CURSO) VALUES ('Paulo Araújo', 'ADS');   